#!/bin/bash -e

echo "--------------------------------"
echo "Installing Dependencies"
echo "--------------------------------"
apt-get update && apt-get upgrade -y

apt-get install -y \
  apt-transport-https \
  autoconf \
  automake \
  bison \
  build-essential \
  ca-certificates \
  curl \
  git \
  gnupg \
  gnupg-agent \
  keychain \
  libc6-dev \
  libssl-dev \
  libtool \
  libxml2-dev \
  libyaml-dev \
  openssl \
  ruby \
  ruby-dev \
  software-properties-common \
  tmux \
  vim \
  zlib1g \
  zlib1g-dev \
  zsh

echo "--------------------------------"
echo "Installing Docker"
echo "--------------------------------"
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
add-apt-repository \
  "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) \
  stable"
apt-get update && apt-get install -y docker-ce docker-ce-cli

curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

base=https://github.com/docker/machine/releases/download/v0.16.0 
curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine
install /tmp/docker-machine /usr/local/bin/docker-machine

echo "--------------------------------"
echo "Updating RubyGems"
echo "--------------------------------"
gem update --system
gem install rails

echo "--------------------------------"
echo "Installing Oh My Zsh"
echo "--------------------------------"
git clone https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

echo "--------------------------------"
echo "Installing Tmuxinator"
echo "--------------------------------"
gem install tmuxinator

echo "--------------------------------"
echo "Installing Vim Plugins"
echo "--------------------------------"
mkdir -p ~/.vim/autoload ~/.vim/bundle
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

git clone https://github.com/lilydjwg/colorizer ~/.vim/bundle
git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree
git clone https://tpope.io/vim/surround.git ~/.vim/bundle/surround

echo "--------------------------------"
echo "Copying Files"
echo "--------------------------------"
cp tmux/sysinfo.sh /usr/bin
cp tmux/.tmux.conf ~/.tmux.conf
mkdir ~/.tmuxinator && cp tmuxinator/erhbg.yml ~/.tmuxinator/erhbg.yml
cp vim/.vimrc ~/.vimrc
mkdir -p ~/.oh-my-zsh/themes && cp zsh/erhbg.zsh-theme ~/.oh-my-zsh/themes/erhbg.zsh-theme
cp zsh/.zshrc ~/.zshrc
mkdir ~/.dir_colors && cp zsh/dircolors.256darksolarized ~/.dir_colors/dircolors.256darksolarized

if grep -q Microsoft /proc/version; then
  winUser=$(echo `/mnt/c/Windows/System32/cmd.exe /c "echo %USERNAME%"` | tr -d '\r')
  if [ -e /mnt/c/Users/$winUser/.hyper.js ]; then
    cp hyper/.hyper-windows.js /mnt/c/Users/$winUser/.hyper.js
  else
    echo "No installation found for Hyper, skip copying config."
  fi
else
  echo "Not a WSL install, will not copy Hyper config."
fi
