#!/bin/bash -e

GO_VERSION="1.18"

echo "--------------------------------"
echo "Bootstrapping directories"
echo "--------------------------------"
mkdir -p '~/Developer/Personal'

echo "--------------------------------"
echo "Installing Homebrew"
echo "--------------------------------"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zshrc
eval "$(/opt/homebrew/bin/brew shellenv)"

echo "--------------------------------"
echo "Installing Dependencies & Shell Stuff"
echo "--------------------------------"
brew install \
  gpg \
  keychain \
  tmux \
  tmuxinator \
  tree

echo "--------------------------------"
echo "Installing Oh My Zsh"
echo "--------------------------------"
if [[ -d ~/.oh-my-zsh ]]; then
  echo "WARN: Oh My Zsh directory exists at ~/.oh-my-zsh, skipping..."
else
  curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh
fi

echo "--------------------------------"
echo "Installing Vim Plugins"
echo "--------------------------------"
if [[ -d ~/.vim/autoload ]] || [[ -d ~/.vim/bundle ]]; then
  echo "WARN: Autoload and Bundle directories already exist under ~/.vim, skipping..."
else
  mkdir -p ~/.vim/autoload ~/.vim/bundle
  curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
  git clone https://github.com/lilydjwg/colorizer ~/.vim/bundle
  git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree
  git clone https://tpope.io/vim/surround.git ~/.vim/bundle/surround
fi

echo "--------------------------------"
echo "Installing Homebrew packages"
echo "--------------------------------"
brew install \
  awscli \
  go@$GO_VERSION

echo "--------------------------------"
echo "Installing Pulumi"
echo "--------------------------------"
brew install pulumi/tap/pulumi

echo "--------------------------------"
echo "Installing tfswitch and terraform"
echo "--------------------------------"
brew install warrensbox/tap/tfswitch
tfswitch `tfswitch -U`

echo "--------------------------------"
echo "Installing granted"
echo "--------------------------------"
brew tap common-fate/granted
brew install granted

echo "--------------------------------"
echo "Copying Files"
echo "--------------------------------"
cp git/.gitconfig* ~
mkdir -p ~/.aws && cp aws/config ~/.aws/config
cp tmux/.tmux.conf ~/.tmux.conf
mkdir -p ~/.tmuxinator && cp tmuxinator/ehassett.yml ~/.tmuxinator/ehassett.yml
cp vim/.vimrc ~/.vimrc
cp vim/colors/monokai_pro/monokai_pro.vim ~/.vim/colors
mkdir -p ~/.oh-my-zsh/themes && cp zsh/ehassett.zsh-theme ~/.oh-my-zsh/themes/ehassett.zsh-theme
cp zsh/.zshrc ~/.zshrc

echo "--------------------------------"
echo "System has been bootstrapped successfully, Happy Hacking!"
echo "--------------------------------"
